################################################################################
################################################################################
###
###  This file is automatically generated. Do not change this file! Changes
###  will get overwritten! Change the source file for "setup.py" instead.
###  This is either 'packageinfo.json' or 'packageinfo.jsonc'
###
################################################################################
################################################################################


from setuptools import setup

def readme():
	with open("README.md", "r", encoding="UTF-8-sig") as f:
		return f.read()

setup(
	author = "Jürgen Knauth",
	author_email = "pubsrc@binary-overflow.de",
	classifiers = [
		"Development Status :: 5 - Production/Stable",
		"License :: OSI Approved :: Apache Software License",
		"Topic :: Software Development :: Testing",
	],
	description = "This python module provides a simple to use infrastructure for running unit tests.",
	download_url = "https://github.com/jkpubsrc/python-module-jk-testing/tarball/0.2020.6.9",
	include_package_data = True,
	install_requires = [
		"jk_logging",
		"jk_temporary",
		"jk_json",
		"graphviz",
		"jinja2",
	],
	keywords = [
		"testing",
		"unittests",
		"tests",
	],
	license = "Apache 2.0",
	name = "jk_testing",
	package_data = {
		"": [
			"data/*",
			"data/html_default/*",
			"data/html_default/files/*",
			"data/html_default/files/images/*",
			"data/html_default/templates/*",
		],
	},
	packages = [
		"jk_testing",
	],
	url = "https://github.com/jkpubsrc/python-module-jk-testing",
	version = "0.2020.6.9",
	zip_safe = False,
	long_description = readme(),
	long_description_content_type="text/markdown",
)
